//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_BuffAttribute: Bright.Config.BeanBase
{
    public config_BuffAttribute(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Attribute = _buf.ReadInt();
        ParamInt = _buf.ReadInt();
        ParamPer = _buf.ReadInt();
        PostInit();
    }

    public static config_BuffAttribute Deserializeconfig_BuffAttribute(ByteBuf _buf)
    {
        return new config_BuffAttribute(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 属性Id
    /// </summary>
    public int Attribute { get; private set; }
    /// <summary>
    /// 整数增益
    /// </summary>
    public int ParamInt { get; private set; }
    /// <summary>
    /// 万分比增益
    /// </summary>
    public int ParamPer { get; private set; }

    public const int __ID__ = -86912724;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attribute:" + Attribute + ","
        + "ParamInt:" + ParamInt + ","
        + "ParamPer:" + ParamPer + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}