//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_Guide: Bright.Config.BeanBase
{
    public config_Guide(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MissionId = _buf.ReadInt();
        IsStrong = _buf.ReadInt();
        Complete = _buf.ReadInt();
        Dialog = _buf.ReadInt();
        ArrowType = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DialogAnchor = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); DialogAnchor.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);GuideBtn = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); GuideBtn.Add(_e0);}}
        HideObj = _buf.ReadString();
        DelayTime = _buf.ReadInt();
        PostInit();
    }

    public static config_Guide Deserializeconfig_Guide(ByteBuf _buf)
    {
        return new config_Guide(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 对应的任务
    /// </summary>
    public int MissionId { get; private set; }
    /// <summary>
    /// 强制引导
    /// </summary>
    public int IsStrong { get; private set; }
    /// <summary>
    /// 完成任务
    /// </summary>
    public int Complete { get; private set; }
    /// <summary>
    /// 引导文本
    /// </summary>
    public int Dialog { get; private set; }
    /// <summary>
    /// 箭头类型
    /// </summary>
    public int ArrowType { get; private set; }
    /// <summary>
    /// 指向目标
    /// </summary>
    public System.Collections.Generic.List<string> DialogAnchor { get; private set; }
    /// <summary>
    /// 引导按钮
    /// </summary>
    public System.Collections.Generic.List<string> GuideBtn { get; private set; }
    /// <summary>
    /// 点击时关闭对象
    /// </summary>
    public string HideObj { get; private set; }
    /// <summary>
    /// 等待时间
    /// </summary>
    public int DelayTime { get; private set; }

    public const int __ID__ = 501757855;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MissionId:" + MissionId + ","
        + "IsStrong:" + IsStrong + ","
        + "Complete:" + Complete + ","
        + "Dialog:" + Dialog + ","
        + "ArrowType:" + ArrowType + ","
        + "DialogAnchor:" + Bright.Common.StringUtil.CollectionToString(DialogAnchor) + ","
        + "GuideBtn:" + Bright.Common.StringUtil.CollectionToString(GuideBtn) + ","
        + "HideObj:" + HideObj + ","
        + "DelayTime:" + DelayTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}