//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_Map: Bright.Config.BeanBase
{
    public config_Map(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Group = _buf.ReadInt();
        Scene = _buf.ReadString();
        Desc = _buf.ReadInt();
        CostItemId = _buf.ReadInt();
        CostItemCount = _buf.ReadInt();
        UnlockLevel = _buf.ReadInt();
        BornPoint = _buf.ReadVector3();
        ScenePicName = _buf.ReadString();
        PostInit();
    }

    public static config_Map Deserializeconfig_Map(ByteBuf _buf)
    {
        return new config_Map(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public int Name { get; private set; }
    /// <summary>
    /// 区域名称
    /// </summary>
    public int Group { get; private set; }
    /// <summary>
    /// 场景名
    /// </summary>
    public string Scene { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public int Desc { get; private set; }
    /// <summary>
    /// 花费道具id
    /// </summary>
    public int CostItemId { get; private set; }
    /// <summary>
    /// 花费道具数量
    /// </summary>
    public int CostItemCount { get; private set; }
    /// <summary>
    /// 解锁等级
    /// </summary>
    public int UnlockLevel { get; private set; }
    /// <summary>
    /// 出生点
    /// </summary>
    public System.Numerics.Vector3 BornPoint { get; private set; }
    /// <summary>
    /// 场景小图片
    /// </summary>
    public string ScenePicName { get; private set; }

    public const int __ID__ = 831811263;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Group:" + Group + ","
        + "Scene:" + Scene + ","
        + "Desc:" + Desc + ","
        + "CostItemId:" + CostItemId + ","
        + "CostItemCount:" + CostItemCount + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "BornPoint:" + BornPoint + ","
        + "ScenePicName:" + ScenePicName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}