//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_Mission: Bright.Config.BeanBase
{
    public config_Mission(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Desc = _buf.ReadInt();
        PreMissionID = _buf.ReadInt();
        UnlockLevel = _buf.ReadInt();
        ShowType = _buf.ReadInt();
        MissionType = _buf.ReadInt();
        GoalType = _buf.ReadInt();
        ParamX = _buf.ReadInt();
        ParamN = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UnlockSystem = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); UnlockSystem.Add(_e0);}}
        AutoSendRewards = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ItemIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Nums = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Nums.Add(_e0);}}
        PostInit();
    }

    public static config_Mission Deserializeconfig_Mission(ByteBuf _buf)
    {
        return new config_Mission(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 任务名称
    /// </summary>
    public int Name { get; private set; }
    /// <summary>
    /// 任务描述
    /// </summary>
    public int Desc { get; private set; }
    /// <summary>
    /// 前置任务Id
    /// </summary>
    public int PreMissionID { get; private set; }
    /// <summary>
    /// 任务解锁等级
    /// </summary>
    public int UnlockLevel { get; private set; }
    /// <summary>
    /// 显示类型
    /// </summary>
    public int ShowType { get; private set; }
    /// <summary>
    /// 任务类型
    /// </summary>
    public int MissionType { get; private set; }
    /// <summary>
    /// 任务目标
    /// </summary>
    public int GoalType { get; private set; }
    /// <summary>
    /// 达成条件
    /// </summary>
    public int ParamX { get; private set; }
    /// <summary>
    /// 达成次数
    /// </summary>
    public int ParamN { get; private set; }
    /// <summary>
    /// 解锁系统
    /// </summary>
    public System.Collections.Generic.List<int> UnlockSystem { get; private set; }
    /// <summary>
    /// 是否自动发放奖励
    /// </summary>
    public int AutoSendRewards { get; private set; }
    /// <summary>
    /// 奖励Id
    /// </summary>
    public System.Collections.Generic.List<int> ItemIds { get; private set; }
    /// <summary>
    /// 奖励数量
    /// </summary>
    public System.Collections.Generic.List<int> Nums { get; private set; }

    public const int __ID__ = 1849155951;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "PreMissionID:" + PreMissionID + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "ShowType:" + ShowType + ","
        + "MissionType:" + MissionType + ","
        + "GoalType:" + GoalType + ","
        + "ParamX:" + ParamX + ","
        + "ParamN:" + ParamN + ","
        + "UnlockSystem:" + Bright.Common.StringUtil.CollectionToString(UnlockSystem) + ","
        + "AutoSendRewards:" + AutoSendRewards + ","
        + "ItemIds:" + Bright.Common.StringUtil.CollectionToString(ItemIds) + ","
        + "Nums:" + Bright.Common.StringUtil.CollectionToString(Nums) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}