//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class category_BuffAttribute: ConfigSingleton<category_BuffAttribute>
{
    private readonly Dictionary<int, config_BuffAttribute> _dataMap;
    private readonly List<config_BuffAttribute> _dataList;
    
    public category_BuffAttribute(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, config_BuffAttribute>();
        _dataList = new List<config_BuffAttribute>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            config_BuffAttribute _v;
            _v = config_BuffAttribute.Deserializeconfig_BuffAttribute(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public category_BuffAttribute()
    {
        throw new System.NotImplementedException();
    }

    public Dictionary<int, config_BuffAttribute> GetAll()
    {
        return _dataMap;
    }
    
    public List<config_BuffAttribute> DataList => _dataList;

    public config_BuffAttribute GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public config_BuffAttribute Get(int key) => _dataMap[key];
    public config_BuffAttribute this[int key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}