//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_RoleMesh: Bright.Config.BeanBase
{
    public config_RoleMesh(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PrefabName = _buf.ReadString();
        FaceIcon = _buf.ReadString();
        SkinName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IgnoreObjs = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); IgnoreObjs.Add(_e0);}}
        PostInit();
    }

    public static config_RoleMesh Deserializeconfig_RoleMesh(ByteBuf _buf)
    {
        return new config_RoleMesh(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 预制名
    /// </summary>
    public string PrefabName { get; private set; }
    /// <summary>
    /// 默认头像
    /// </summary>
    public string FaceIcon { get; private set; }
    /// <summary>
    /// 皮肤节点名
    /// </summary>
    public string SkinName { get; private set; }
    /// <summary>
    /// 忽略的Render节点
    /// </summary>
    public System.Collections.Generic.List<string> IgnoreObjs { get; private set; }

    public const int __ID__ = -1865712640;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PrefabName:" + PrefabName + ","
        + "FaceIcon:" + FaceIcon + ","
        + "SkinName:" + SkinName + ","
        + "IgnoreObjs:" + Bright.Common.StringUtil.CollectionToString(IgnoreObjs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}