//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_SystemUnlock: Bright.Config.BeanBase
{
    public config_SystemUnlock(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UnlockLevel = _buf.ReadInt();
        Name = _buf.ReadInt();
        PanelName = _buf.ReadString();
        PostInit();
    }

    public static config_SystemUnlock Deserializeconfig_SystemUnlock(ByteBuf _buf)
    {
        return new config_SystemUnlock(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 解锁等级
    /// </summary>
    public int UnlockLevel { get; private set; }
    /// <summary>
    /// 系统名
    /// </summary>
    public int Name { get; private set; }
    /// <summary>
    /// 界面名
    /// </summary>
    public string PanelName { get; private set; }

    public const int __ID__ = 1861661776;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "Name:" + Name + ","
        + "PanelName:" + PanelName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}