//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_UISwitch: Bright.Config.BeanBase
{
    public config_UISwitch(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        SystemId = _buf.ReadInt();
        SheetId = _buf.ReadInt();
        PostInit();
    }

    public static config_UISwitch Deserializeconfig_UISwitch(ByteBuf _buf)
    {
        return new config_UISwitch(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public int Name { get; private set; }
    /// <summary>
    /// 跳转的系统Id
    /// </summary>
    public int SystemId { get; private set; }
    /// <summary>
    /// 页签Id
    /// </summary>
    public int SheetId { get; private set; }

    public const int __ID__ = -995907771;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "SystemId:" + SystemId + ","
        + "SheetId:" + SheetId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}