//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_ServerSettings: Bright.Config.BeanBase
{
    public config_ServerSettings(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ServerAdress = _buf.ReadString();
        CDNAddress = _buf.ReadString();
        PostInit();
    }

    public static config_ServerSettings Deserializeconfig_ServerSettings(ByteBuf _buf)
    {
        return new config_ServerSettings(_buf);
    }

    /// <summary>
    /// _Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 服务器地址
    /// </summary>
    public string ServerAdress { get; private set; }
    /// <summary>
    /// 资源服地址
    /// </summary>
    public string CDNAddress { get; private set; }

    public const int __ID__ = 1398925123;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ServerAdress:" + ServerAdress + ","
        + "CDNAddress:" + CDNAddress + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}