//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_RoleInit: Bright.Config.BeanBase
{
    public config_RoleInit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ParamInts = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ParamInts.Add(_e0);}}
        PostInit();
    }

    public static config_RoleInit Deserializeconfig_RoleInit(ByteBuf _buf)
    {
        return new config_RoleInit(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 参数
    /// </summary>
    public System.Collections.Generic.List<int> ParamInts { get; private set; }

    public const int __ID__ = -1865823453;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ParamInts:" + Bright.Common.StringUtil.CollectionToString(ParamInts) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}