//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_RoleCreateParams: Bright.Config.BeanBase
{
    public config_RoleCreateParams(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        ItemName = _buf.ReadInt();
        Icon = _buf.ReadString();
        Param = _buf.ReadString();
        PostInit();
    }

    public static config_RoleCreateParams Deserializeconfig_RoleCreateParams(ByteBuf _buf)
    {
        return new config_RoleCreateParams(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 类型名
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public int ItemName { get; private set; }
    /// <summary>
    /// 图片名
    /// </summary>
    public string Icon { get; private set; }
    /// <summary>
    /// 参数
    /// </summary>
    public string Param { get; private set; }

    public const int __ID__ = 323386549;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "ItemName:" + ItemName + ","
        + "Icon:" + Icon + ","
        + "Param:" + Param + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}