//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_Buff: Bright.Config.BeanBase
{
    public config_Buff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        ConfId = _buf.ReadInt();
        Duration = _buf.ReadInt();
        StackCount = _buf.ReadInt();
        PostInit();
    }

    public static config_Buff Deserializeconfig_Buff(ByteBuf _buf)
    {
        return new config_Buff(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 配置Id
    /// </summary>
    public int ConfId { get; private set; }
    /// <summary>
    /// 持续时间
    /// </summary>
    public int Duration { get; private set; }
    /// <summary>
    /// 叠加层数
    /// </summary>
    public int StackCount { get; private set; }

    public const int __ID__ = 16036688;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "ConfId:" + ConfId + ","
        + "Duration:" + Duration + ","
        + "StackCount:" + StackCount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}