//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_Gameparam: Bright.Config.BeanBase
{
    public config_Gameparam(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Paramint = _buf.ReadInt();
        PostInit();
    }

    public static config_Gameparam Deserializeconfig_Gameparam(ByteBuf _buf)
    {
        return new config_Gameparam(_buf);
    }

    /// <summary>
    /// _Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 参数1
    /// </summary>
    public int Paramint { get; private set; }

    public const int __ID__ = -1305188610;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Paramint:" + Paramint + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}