//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_PlayerLevel: Bright.Config.BeanBase
{
    public config_PlayerLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Exp = _buf.ReadInt();
        PostInit();
    }

    public static config_PlayerLevel Deserializeconfig_PlayerLevel(ByteBuf _buf)
    {
        return new config_PlayerLevel(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 经验需求
    /// </summary>
    public int Exp { get; private set; }

    public const int __ID__ = -1319933050;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Exp:" + Exp + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}