//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_Language: Bright.Config.BeanBase
{
    public config_Language(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Text = _buf.ReadString();
        PostInit();
    }

    public static config_Language Deserializeconfig_Language(ByteBuf _buf)
    {
        return new config_Language(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 文本
    /// </summary>
    public string Text { get; private set; }

    public const int __ID__ = 1082470357;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Text:" + Text + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}