//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class config_ResolveItem: Bright.Config.BeanBase
{
    public config_ResolveItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemIDs = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ItemIDs[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemNums = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ItemNums[__index0] = __e0;}}
        PostInit();
    }

    public static config_ResolveItem Deserializeconfig_ResolveItem(ByteBuf _buf)
    {
        return new config_ResolveItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 出售获得的道具ID
    /// </summary>
    public int[] ItemIDs { get; private set; }
    /// <summary>
    /// 道具数量
    /// </summary>
    public int[] ItemNums { get; private set; }

    public const int __ID__ = 93409666;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ItemIDs:" + Bright.Common.StringUtil.CollectionToString(ItemIDs) + ","
        + "ItemNums:" + Bright.Common.StringUtil.CollectionToString(ItemNums) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}